parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - 'prettier'
  - 'react'
  - 'react-hooks'
  - 'tailwindcss'
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:prettier/recommended'
  - 'prettier'
  - 'plugin:tailwindcss/recommended'
settings:
  react:
    version: detect
env:
  browser: true
  node: true
  es6: true
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
  project: './tsconfig.json'
rules:
  'react/prop-types': off
  'react/react-in-jsx-scope': off
  'react/display-name': off
  'react-hooks/rules-of-hooks': error
  '@typescript-eslint/no-floating-promises': error
  '@typescript-eslint/no-unnecessary-qualifier': error
  '@typescript-eslint/no-empty-interface': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/promise-function-async': error
  '@typescript-eslint/require-await': error
  '@typescript-eslint/ban-ts-ignore': off
  '@typescript-eslint/no-use-before-define':
    - error
    - functions: false
      classes: false
      enums: true
      variables: true
      typedefs: true
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-namespace': off
